site_name: patCit
site_description: Building a Comprehensive Patent Citations Dataset
site_author: Cyril Verluise
site_url: https://cverluise.github.io/PatCit/

# Repository
repo_name: cverluise/PatCit
repo_url: https://github.com/cverluise/PatCit


# Copyright
copyright: Copyright & copy; 2019-2020 Gaétan de Rassenfosse and Cyril Verluise

# Theme
theme:
  name: material
  language: en
  favicon: img/patcit-logo.svg
  features:
    - navigation.tabs
    - navigation.sections
  palette:
    primary: teal
    accent: teal
  logo:
    img/patcit-logo.svg

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - footnotes
  - toc:
      permalink: true
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      linenums: true
  - pymdownx.arithmatex:
        generic: true
  - pymdownx.tasklist:
      custom_checkbox: true

# Plugins
plugins:
  - search:
      lang: en

# JS
extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Footer
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/cyrilverluise
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/cyril-verluise-80184347/
    - icon: fontawesome/brands/github
      link: https://cverluise.github.io/PatCit/

# Page tree

nav:
  - About: index.md
  - Team: team.md
  - Awesome: awesome.md
  - Data:
    - Download: download.md
    - Explore: explore.md
    - Versions: versions.md
  - Developper:
#    - Recipes: recipes.md
    - Contributions: contributing.md
    - Code of Conduct: code-of-conduct.md
#  - How it works:
#     - Extract, Parse, Consolidate: extract-parse-consolidate.md
#     - Classify: classify.md
  #  - Vocabulary: vocabulary.md
  - Licenses:
    - MIT: license-mit.md
    - CC-BY-4: license-cc.md
